name: Deploy Website

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger the deployment from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Deploy to GitHub Pages
        run: |
          mkdir public
          cp -r * public/
          echo 'Your GitHub Pages site is ready!' > public/index.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
